install:
		./gradlew clean install

run-dist:
		./build/install/app/bin/app

run:
		./gradlew run

lint:
		./gradlew checkstyleMain

test:
		./gradlew test

check-deps:
		./gradlew dependencyUpdates -Drevision=release
